
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\SY 2024-2025\SECOND SEMESTER\CC 15_Application Development and Emerging Technologies\Qtkinter Final Proj GUI 2\TO UPLOAD_With Email TextBox\build\assets\frame12")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x706")
window.configure(bg = "#FFB37F")


canvas = Canvas(
    window,
    bg = "#FFB37F",
    height = 706,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    533.0,
    186.0,
    anchor="nw",
    text="RESET PASSWORD",
    fill="#040404",
    font=("Inter Bold", 51 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    bg="#FFB37F",  # Match the background color of the canvas
    activebackground="#FFB37F",  # Ensure no background color change when clicked
    cursor="hand2"  # Change cursor to hand when hovering
)
button_1.place(
    x=434.0,
    y=175.0,
    width=72.0,
    height=72.0
)

canvas.create_text(
    434.0,
    287.0,
    anchor="nw",
    text="Please enter your email:",
    fill="#040404",
    font=("Inter Bold", 27 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    720.0,
    361.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Inter Regular", 24 * -1),
)
entry_1.place(
    x=459.0,
    y=329.0,
    width=522.0,
    height=63.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
    bg="#FFB37F",  # Match the background color of the canvas
    activebackground="#FFB37F",  # Ensure no background color change when clicked
    cursor="hand2"  # Change cursor to hand when hovering

)
button_2.place(
    x=627.0,
    y=434.0,
    width=185.0,
    height=48.0
)
window.resizable(False, False)
window.mainloop()
