
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\SY 2024-2025\SECOND SEMESTER\CC 15_Application Development and Emerging Technologies\Qtkinter Final Proj GUI 2\Adjusted Employee Widget\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("299x177")
window.configure(bg = "#FFF4ED")


canvas = Canvas(
    window,
    bg = "#FFF4ED",
    height = 177,
    width = 299,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    150.0,
    120.0,
    image=image_image_1
)

canvas.create_text(
    24.0,
    25.0,
    anchor="nw",
    text="{Employee Full Name}",
    fill="#040404",
    font=("Inter Bold", 17 * -1)
)

canvas.create_text(
    24.0,
    56.0,
    anchor="nw",
    text="{Employee Department}",
    fill="#737373",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    70.0,
    99.0,
    anchor="nw",
    text="{Employee Address}",
    fill="#212121",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    70.0,
    125.0,
    anchor="nw",
    text="{Employee Phone Number}",
    fill="#212121",
    font=("Inter Bold", 12 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    49.0,
    107.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    49.0,
    133.0,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
